version: '3.8'

services:
  kafka1:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka1
    ports:
      - "9092:9092"
    volumes:
      - ./configs/kafka1.properties:/etc/kafka/kafka.properties
      - ./scripts/start-kafka.sh:/start-kafka.sh
      - ./data/kafka1:/tmp/kraft-combined-logs
    command: ["bash", "-c", "/start-kafka.sh"]
    networks:
      - kafka-network

  kafka2:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka2
    ports:
      - "9094:9092"
    volumes:
      - ./configs/kafka2.properties:/etc/kafka/kafka.properties
      - ./scripts/start-kafka.sh:/start-kafka.sh
      - ./data/kafka2:/tmp/kraft-combined-logs
    command: ["bash", "-c", "/start-kafka.sh"]
    networks:
      - kafka-network

#  kafka3:
#    image: confluentinc/cp-kafka:7.3.0
#    container_name: kafka3
#    ports:
#      - "9096:9092"
#    volumes:
#      - ./configs/kafka3.properties:/etc/kafka/kafka.properties
#      - ./scripts/start-kafka.sh:/start-kafka.sh
#      - ./data/kafka3:/tmp/kraft-combined-logs
#    command: ["bash", "-c", "/start-kafka.sh"]
#    networks:
#      - kafka-network

networks:
  kafka-network:
    driver: bridge